apiVersion: v1
kind: Service
metadata:
  name: elixir-plug-poc
  labels:
    app: elixir-plug-poc
spec:
  ports:
  - port: 4000
    name: web
  clusterIP: None
  selector:
    app: elixir-plug-poc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elixir-plug-poc
spec:
  serviceName: "elixir-plug-poc"
  replicas: 2
  selector:
    matchLabels:
      app: elixir-plug-poc
  template:
    metadata:
      labels:
        app: elixir-plug-poc
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '4000'
    spec:
      containers:
      - name: elixir-plug-poc
        image: binarytemple/elixir_plug_poc
        args:
          - foreground
        env:
          - name: ERLANG_COOKIE
            value: "cookie"
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        volumeMounts:
        - name: debug
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: debug
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 200m