kind: Secret
apiVersion: v1
metadata:
  name: monitoring
  namespace: monitoring
  labels:
    app: grafana
data:
  admin-password: YWRtaW4=                                                                                                                                                        
  admin-username: YWRtaW4=                                                                                                                                                        
  foo: YmFy                                                                                                                                                                       
  smtp-host: bG9jYWxob3N0OjI1                                                                                                                                                     
  smtp-password: YWRtaW4=                                                                                                                                                         
  smtp-username: YWRtaW4=    

type: Opaque
