apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  namespace: testing-kube-logging
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: count
          image: busybox
          args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
